use borsh::{BorshDeserialize, BorshSerialize};

/// ZK-STARK proof generated by Cairo program execution.
#[derive(Clone, Debug, BorshSerialize, BorshDeserialize)]
pub struct CairoProof {
    /// Serialized proof data
    pub proof_bytes: Vec<u8>,
    /// Program address that generated this proof
    pub program_address: [u8; 32],
}

#[derive(Clone, Debug, Default, BorshSerialize, BorshDeserialize)]
pub struct TransactionEffects {
    /// Return values from program executions (program address -> return data)
    pub return_values: Vec<(u64, Vec<u8>)>, // (index, data)
    /// Published program addresses
    pub published_programs: Vec<u64>, // indices of published programs
    /// ZK-STARK proofs generated by Cairo program executions
    pub proofs: Vec<(u64, CairoProof)>, // (program_index, proof)
}
